### ISSUE TITLE
Curiosity: why do you add the BoxHeaderSize to offset at ReadBoxAt?

### ISSUE THREAD

**Issue by leandromoreira** [alfg/mp4#12]
https://github.com/alfg/mp4/blob/de9679deb8f32c1920c41d3acd9512515011bc44/atom/box.go#L61

<img width="545" alt="image" src="https://user-images.githubusercontent.com/55913/73113280-ba307600-3ef1-11ea-9ff3-b903ed44bdfa.png">

It doesn't seem necessary since the real addition happens in the `readBoxes` function

**Comment by leandromoreira** [comment]
By the way this is an awesome mp4 parser, it's perfect to teach mp4 for people.

**Comment by alfg** [comment]
Hi @leandromoreira,

Good catch! I must have added by mistake when figuring how to parse the box headers.

And thanks for the kind words! I created this project to learn more about the isobmff box structure. 

Also, thank you for your guides too! Specifically `digital_video_introduction` and `ffmpeg-libav-tutorial`. I've both of those projects as a learning resource for `libav`. 🙂

**Comment by alfg** [comment]
Fixed on https://github.com/alfg/mp4/commit/55ce94e6a3b372bd45beeadafeb2b935d9d70378
