### ISSUE TITLE
Unnecessary Println in code

### ISSUE THREAD

**Issue by condorcet** [alfg/mp4#14]
Hi! Thank you for the project, nice work!

Please notice there is using of unnecessary `fmt.Println` https://github.com/alfg/mp4/blob/5d5af3e20d076ece7fc5a3d16ecf0a3904808970/atom/moov.go#L53 It makes parsing a little bit noisy with no reason :)

**Comment by alfg** [comment]
Oops, good catch! I'll clean up all the `fmt.Println`'s soon!

Thanks!

**Comment by alfg** [comment]
Fixed on #15.

**Comment by condorcet** [comment]
@alfg Thank you!
