### ISSUE TITLE
Implement a mp4.open functionality for multipart upload

### ISSUE THREAD

**Issue by kafan1986** [alfg/mp4#16]
file, fileHeader, err := r.FormFile("uploadedfile")

The multipart file is in memory and not on disk. Can you provide a functionality that directly can work on this data?

**Comment by alfg** [comment]
Hi @kafan1986. I'll look into implementing a reader soon.

Thanks!

**Comment by alfg** [comment]
Added two new functions on #17 to support opening from reader or bytes.

I've added an HTTP example:
https://github.com/alfg/mp4/blob/master/examples/server_example/main.go

**Comment by kafan1986** [comment]
@alfg Thanks for such a quick solution. Closing the issue now.
