### ISSUE TITLE
Suggestion: Fix command for git clone on the README.md / get rid of WIndows-specific paths

### ISSUE THREAD

**Issue by GwynethLlewelyn** [alfg/mp4#5]
I'm compiling your nice little package under macOS Catalina 10.15.2 Beta, and your instructions on the `README.md` require some slight changes:

- When using `git` version 2.23.0, the correct command line should be `git clone https://github.com/alfg/mp4` (i.e. the `https://` bit seems to be mandatory)
- Un*x operating systems do not use the backslash `\` as directory separator; `go` should actually be able to use `/` for Windows as well (internally converting it)
- Similarly, the `.exe` extension is specific for Windows; Unix don't require these extensions (but it's possible to add them, of course, so long as people don't forget to use the extension when running the compiled application)

That's it for now. I'm just browsing through your package to learn a bit about how to read MOV/MP4 files in order to try to fix a movie I've got which has a missing MOOV atom (or, worse, a broken one...).

**Comment by alfg** [comment]
Hi @GwynethLlewelyn,

Thanks for catching these! I'll fix the readme soon. I should have spent more time proofing the commands. 😵

**Comment by alfg** [comment]
Fixed! Thanks!
